services:
  editor:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/workspace
      - ~/.bashrc:/root/.bashrc
      - type: bind
        source: /home/${USER}/.ssh
        target: /root/.ssh
        consistency: cached
